// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ooWkKYpQkWmYsN1A744BKSxdqoXD0Ks',
    appId: '1:648191628661:web:b9c7487e9397cd16b0af3c',
    messagingSenderId: '648191628661',
    projectId: 'unitalk-561c1',
    authDomain: 'unitalk-561c1.firebaseapp.com',
    storageBucket: 'unitalk-561c1.firebasestorage.app',
    measurementId: 'G-WXG7V2N3XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNDSfvBvAbWkv8ZqpxBoLrc7zi21fJXuc',
    appId: '1:648191628661:android:8bbec4506a67adeab0af3c',
    messagingSenderId: '648191628661',
    projectId: 'unitalk-561c1',
    storageBucket: 'unitalk-561c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3yG1Ab0G9fJ8evCtcSLuc48xtbJKC02s',
    appId: '1:648191628661:ios:bdd505a87c4c0ccdb0af3c',
    messagingSenderId: '648191628661',
    projectId: 'unitalk-561c1',
    storageBucket: 'unitalk-561c1.firebasestorage.app',
    iosBundleId: 'com.devvibe.unitalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3yG1Ab0G9fJ8evCtcSLuc48xtbJKC02s',
    appId: '1:648191628661:ios:bdd505a87c4c0ccdb0af3c',
    messagingSenderId: '648191628661',
    projectId: 'unitalk-561c1',
    storageBucket: 'unitalk-561c1.firebasestorage.app',
    iosBundleId: 'com.devvibe.unitalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_ooWkKYpQkWmYsN1A744BKSxdqoXD0Ks',
    appId: '1:648191628661:web:785b157813e940e3b0af3c',
    messagingSenderId: '648191628661',
    projectId: 'unitalk-561c1',
    authDomain: 'unitalk-561c1.firebaseapp.com',
    storageBucket: 'unitalk-561c1.firebasestorage.app',
    measurementId: 'G-DVVD697E0R',
  );
}
